# Generated by Django 5.1.2 on 2024-10-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Никнейм'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Никнейм в Telegram'),
        ),
    ]
