# Generated by Django 5.1.2 on 2024-10-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_nickname_profile_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='login',
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Логин'),
        ),
    ]
