# Generated by Django 5.1.2 on 2024-10-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_login_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Никнейм в Telegram'),
        ),
    ]
